!> FRUIT unit test framework helper subroutines.
!! Based on driver code auto-generated by FRUIT's Ruby pre-processor.

!! Copyright 2014 The University of Edinburgh.
!!
!! Licensed under the Apache License, Version 2.0 (the "License"); 
!! you may not use this file except in compliance with the License. 
!! You may obtain a copy of the License at
!!
!!   http://www.apache.org/licenses/LICENSE-2.0
!!
!! Unless required by applicable law or agreed to in writing, software 
!! distributed under the License is distributed on an "AS IS" BASIS, 
!! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
!! implied. See the License for the specific language governing
!! permissions and limitations under the License.

module fruit_helpers

  use fruit
  implicit none

contains

  !> Invoke a test case sub-routine of a test suite, invoking the
  !! suite's setup sub-routine first, and its teardown sub-routine
  !! after. This sub-routine was abstracted out from "basket" code
  !! auto-generated by FRUIT's Ruby pre-processor.
  subroutine run_fruit_test_case(test_case,test_case_name, &
    setup,teardown,test_suite_name)
    interface
      subroutine test_case()
      end subroutine
    end interface
    character(*),intent(in) :: test_case_name
    interface
      subroutine setup()
      end subroutine
    end interface
    interface
      subroutine teardown()
      end subroutine
    end interface
    character(*),intent(in) :: test_suite_name

    call setup()
    write(*,'(/A,A,A,A)') 'Running: ',test_suite_name,':',test_case_name
    call set_unit_name(test_case_name)
    call run_test_case(test_case,test_case_name)
    if (.not. is_case_passed()) then
      call case_failed_xml(test_case_name,test_suite_name)
    else
      call case_passed_xml(test_case_name,test_suite_name)
    end if
    call teardown()
  end subroutine run_fruit_test_case

end module fruit_helpers
